import { Opportunity, CSRGrant, UserProfile, Post, CommunityEvent, NotificationItem } from './types';

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-1',
    title: 'Weekend Urban Reforestation & Native Seed Planting',
    description: 'Join community conservationists to restore native biodiversity and canopy cover across distressed urban riverbanks.',
    organizationId: 'ngo-1',
    organizationName: 'GreenCanopy Initiative',
    organizationType: 'ngo',
    type: 'volunteering',
    status: 'urgent',
    location: 'Metro Parklands, East Basin',
    isRemote: false,
    cause: 'Environment',
    skillsRequired: ['Planting', 'Field Logistics', 'Physical Stamina'],
    startDate: '2026-09-12',
    commitmentHours: '4 hours / weekend',
    capacityNeeded: 25,
    capacityFilled: 18,
    featured: true,
    corporateSponsor: 'EcoTech Partners',
  },
  {
    id: 'opp-2',
    title: 'STEM Mentorship for Underrepresented Youth',
    description: 'Mentor secondary students in introductory robotics, coding logic, and science project presentations once a week.',
    organizationId: 'ngo-2',
    organizationName: 'CodeForward Foundation',
    organizationType: 'ngo',
    type: 'mentorship',
    status: 'open',
    location: 'Hybrid (Online + Civic Library)',
    isRemote: true,
    cause: 'Education',
    skillsRequired: ['Python', 'Basic Math', 'Youth Mentoring'],
    startDate: '2026-09-20',
    commitmentHours: '2 hours / week',
    capacityNeeded: 12,
    capacityFilled: 8,
    featured: true,
  },
  {
    id: 'opp-3',
    title: 'Food Rescue & Mobile Pantry Distribution',
    description: 'Support weekly surplus food collections from regional grocers and distribute nutritious pantry baskets to families.',
    organizationId: 'ngo-3',
    organizationName: 'TableOfHope Network',
    organizationType: 'ngo',
    type: 'volunteering',
    status: 'open',
    location: 'Central Distribution Hub, Ward 4',
    isRemote: false,
    cause: 'Hunger Relief',
    skillsRequired: ['Inventory Sorting', 'Safe Food Handling', 'Driver (Optional)'],
    startDate: '2026-09-08',
    commitmentHours: '3 hours / shift',
    capacityNeeded: 30,
    capacityFilled: 22,
  },
  {
    id: 'opp-4',
    title: 'Non-Profit Financial Systems & Bookkeeping Audit',
    description: 'Corporate accounting professionals providing pro-bono assistance to upgrade financial controls for 5 local relief shelters.',
    organizationId: 'corp-1',
    organizationName: 'Apex Capital CSR',
    organizationType: 'corporate',
    type: 'skills_based',
    status: 'open',
    location: 'Remote',
    isRemote: true,
    cause: 'Governance & Capacity',
    skillsRequired: ['Accounting', 'QuickBooks', 'Nonprofit Reporting'],
    startDate: '2026-10-01',
    commitmentHours: '5 hours / month',
    capacityNeeded: 6,
    capacityFilled: 4,
    corporateSponsor: 'Apex Capital Advisors',
  },
  {
    id: 'opp-5',
    title: 'Community Health Awareness & Preventive Screening Camp',
    description: 'Coordinate volunteer queues, translate intake instructions, and assist licensed community nurses during weekend health fairs.',
    organizationId: 'ngo-4',
    organizationName: 'Civic Health Coalition',
    organizationType: 'ngo',
    type: 'volunteering',
    status: 'urgent',
    location: 'South Community Centre',
    isRemote: false,
    cause: 'Healthcare',
    skillsRequired: ['Patient Intake', 'Bilingual (Helpful)', 'First Aid'],
    startDate: '2026-09-19',
    commitmentHours: '6 hours / day',
    capacityNeeded: 15,
    capacityFilled: 11,
  },
  {
    id: 'opp-6',
    title: 'Digital Literacy for Seniors and Retirees',
    description: 'Help senior citizens navigate smartphones, verify online safety, and access telehealth portals with patience and care.',
    organizationId: 'ngo-2',
    organizationName: 'CodeForward Foundation',
    organizationType: 'ngo',
    type: 'mentorship',
    status: 'in_review',
    location: 'Elder Care Hub, West Gate',
    isRemote: false,
    cause: 'Digital Inclusion',
    skillsRequired: ['Patient Communication', 'Smartphone Basics', 'Empathy'],
    startDate: '2026-09-25',
    commitmentHours: '2 hours / week',
    capacityNeeded: 10,
    capacityFilled: 10,
  }
];

export const MOCK_GRANTS: CSRGrant[] = [
  {
    id: 'grant-1',
    title: '2026 Renewable Community Microgrid Grant',
    corporateName: 'TerraPower Utilities',
    description: 'Capital assistance and engineering mentorship for registered non-profits deploying rooftop solar in underserved community centres.',
    budgetScope: '$45,000 direct equipment & deployment grant',
    focusArea: 'Environment & Clean Energy',
    eligibleNgosCount: 14,
    deadline: '2026-10-15',
    status: 'active',
  },
  {
    id: 'grant-2',
    title: 'Digital Classrooms Equipment & Broadband Subsidy',
    corporateName: 'Nexus Tech Global',
    description: 'Providing hardware kits (refurbished laptops, smart displays) and 2-year connectivity funding for regional educational charities.',
    budgetScope: '$30,000 in-kind hardware & telecom credit',
    focusArea: 'Education & Digital Literacy',
    eligibleNgosCount: 22,
    deadline: '2026-11-01',
    status: 'active',
  },
  {
    id: 'grant-3',
    title: 'Emergency Cold Storage Logistics Fund',
    corporateName: 'Kestrel Logistics Corp',
    description: 'Grant to strengthen refrigerated transit and storage capacity for local food banks during extreme temperature months.',
    budgetScope: '$20,000 logistics support',
    focusArea: 'Hunger Relief',
    eligibleNgosCount: 9,
    deadline: '2026-09-30',
    status: 'evaluating',
  }
];

export const MOCK_PROFILES: UserProfile[] = [
  {
    id: 'ngo-1',
    email: 'contact@greencanopy.org',
    fullName: 'GreenCanopy Initiative',
    role: 'ngo',
    organizationName: 'GreenCanopy Initiative',
    bio: 'Dedicated to urban green spaces, native reforestation, and environmental equity across metropolitan corridors since 2018.',
    location: 'Portland, OR',
    website: 'https://greencanopy.example.org',
    causes: ['Environment', 'Conservation', 'Climate Action'],
    verified: true,
    createdAt: '2024-01-15',
  },
  {
    id: 'ngo-2',
    email: 'team@codeforward.org',
    fullName: 'CodeForward Foundation',
    role: 'ngo',
    organizationName: 'CodeForward Foundation',
    bio: 'Providing zero-cost computing education, coding mentoring, and hardware access to public school students in Title 1 districts.',
    location: 'Chicago, IL',
    website: 'https://codeforward.example.org',
    causes: ['Education', 'Digital Inclusion', 'Youth Empowerment'],
    verified: true,
    createdAt: '2023-08-20',
  },
  {
    id: 'ngo-3',
    email: 'info@tableofhope.org',
    fullName: 'TableOfHope Network',
    role: 'ngo',
    organizationName: 'TableOfHope Network',
    bio: 'Distributing over 15,000 nutritious meals weekly through community food recovery partnerships with local regional producers.',
    location: 'Atlanta, GA',
    website: 'https://tableofhope.example.org',
    causes: ['Hunger Relief', 'Food Security', 'Community Well-being'],
    verified: true,
    createdAt: '2023-04-10',
  },
  {
    id: 'corp-1',
    email: 'csr@apexcapital.example.com',
    fullName: 'Apex Capital CSR Division',
    role: 'corporate',
    organizationName: 'Apex Capital Advisors',
    bio: 'Championing employee pro-bono governance, non-profit financial transparency, and matching volunteer grants across 12 cities.',
    location: 'New York, NY',
    website: 'https://apexcapital.example.com/csr',
    causes: ['Governance & Capacity', 'Education', 'Community Reinvestment'],
    verified: true,
    createdAt: '2022-11-05',
  },
  {
    id: 'corp-2',
    email: 'impact@terrapower.example.com',
    fullName: 'TerraPower Community Affairs',
    role: 'corporate',
    organizationName: 'TerraPower Utilities',
    bio: 'Investing 2% of annual operating margins in grassroot renewable energy transition, solar grants, and community microgrids.',
    location: 'Denver, CO',
    website: 'https://terrapower.example.com/impact',
    causes: ['Environment & Clean Energy', 'Climate Resilience'],
    verified: true,
    createdAt: '2023-02-14',
  }
];

export const CAUSE_OPTIONS = [
  'All Causes',
  'Environment',
  'Education',
  'Hunger Relief',
  'Healthcare',
  'Digital Inclusion',
  'Governance & Capacity',
  'Youth Empowerment'
];

/* =========================================================================
   Community Posts & Impact Stories Mock Data
   ========================================================================= */

export const MOCK_POSTS: Post[] = [
  {
    id: 'post-1',
    ngoProfileId: 'ngo-1',
    ngoName: 'GreenCanopy Initiative',
    type: 'IMPACT_STORY',
    title: 'Spring Watershed Restoration: 1,850 Native Trees Seeded',
    body: 'Thanks to 85 weekend volunteers and seedling support from EcoTech Partners, we completed the phase-two revegetation of the Lower Willamette riparian corridor. Soil moisture sensors indicate an 18% improvement in retention over bare ground.',
    cause: 'Environment',
    impactMetric: '1,850 Native Trees Planted',
    visibility: 'PUBLIC',
    isPublished: true,
    publishedAt: '2026-09-02T14:30:00Z',
    createdAt: '2026-09-02T10:00:00Z',
  },
  {
    id: 'post-2',
    ngoProfileId: 'ngo-2',
    ngoName: 'CodeForward Foundation',
    type: 'POST',
    title: 'Autumn Robotics Lab: Welcoming 35 New Middle School Scholars',
    body: 'We officially kicked off our weekend robotics cohort across three community civic branches this Saturday. Mentors from university computing labs and corporate software volunteers are guiding students through mechanical assembly and introductory Python logic.',
    cause: 'Education',
    visibility: 'PUBLIC',
    isPublished: true,
    publishedAt: '2026-09-01T18:00:00Z',
    createdAt: '2026-09-01T15:00:00Z',
  },
  {
    id: 'post-3',
    ngoProfileId: 'ngo-3',
    ngoName: 'TableOfHope Network',
    type: 'IMPACT_STORY',
    title: 'Surplus Food Rescue Milestone: 42,000 lbs Diverted in August',
    body: 'In August alone, our volunteer transit drivers and grocery partners rescued 42,300 lbs of fresh produce and shelf-stable foods from landfill diversion. 3,400 vulnerable households received emergency fresh pantry hampers with zero administrative charges.',
    cause: 'Hunger Relief',
    impactMetric: '42,300 lbs Surplus Food Rescued',
    visibility: 'PUBLIC',
    isPublished: true,
    publishedAt: '2026-08-31T09:15:00Z',
    createdAt: '2026-08-31T08:00:00Z',
  },
  {
    id: 'post-4',
    ngoProfileId: 'ngo-1',
    ngoName: 'GreenCanopy Initiative',
    type: 'POST',
    title: 'Equipment Arrival: New Tree Transplanters & Field First-Aid Kits',
    body: 'Our field equipment store has been fully restocked with ergonomically designed planting spades, child-safe soil screens, and field hydration packs funded through the 2025 Regional Green Fund.',
    cause: 'Environment',
    visibility: 'VOLUNTEER_ONLY',
    isPublished: true,
    publishedAt: '2026-08-28T11:00:00Z',
    createdAt: '2026-08-28T10:00:00Z',
  },
  {
    id: 'post-5',
    ngoProfileId: 'ngo-2',
    ngoName: 'CodeForward Foundation',
    type: 'IMPACT_STORY',
    title: 'First-Generation College Admissions: 14 STEM Scholars Funded',
    body: 'Proud to announce that all 14 graduating seniors in our three-year high school coding fellowship have earned accredited STEM undergraduate admissions, with 8 securing full tuition scholarships.',
    cause: 'Education',
    impactMetric: '14 Full College Admissions',
    visibility: 'CORPORATE_ONLY',
    isPublished: true,
    publishedAt: '2026-08-25T16:45:00Z',
    createdAt: '2026-08-25T14:00:00Z',
  }
];

/* =========================================================================
   Community Events Mock Data (Ready for upcoming Event Module)
   ========================================================================= */

export const MOCK_EVENTS: CommunityEvent[] = [
  {
    id: 'evt-1',
    ngoProfileId: 'ngo-1',
    ngoName: 'GreenCanopy Initiative',
    title: 'Community Urban Canopy Orientation & Tree Care Workshop',
    description: 'Hands-on briefing covering native tree sapling care, mulch distribution techniques, and volunteer safety on parkland slopes.',
    eventDate: '2026-09-18T10:00:00Z',
    location: 'Civic Arboretum, Classroom 2',
    isRemote: false,
    capacity: 40,
    rsvpCount: 28,
    cause: 'Environment',
    isPublished: true,
    createdAt: '2026-08-20T12:00:00Z',
  },
  {
    id: 'evt-2',
    ngoProfileId: 'ngo-2',
    ngoName: 'CodeForward Foundation',
    title: 'Virtual STEM Mentor Onboarding & Child Safety Training',
    description: 'Mandatory online session for upcoming coding and robotics mentors reviewing lesson plans, inclusive pedagogy, and safety protocols.',
    eventDate: '2026-09-15T18:00:00Z',
    location: 'Online Webinar',
    isRemote: true,
    capacity: 60,
    rsvpCount: 44,
    cause: 'Education',
    isPublished: true,
    createdAt: '2026-08-22T09:00:00Z',
  }
];

/* =========================================================================
   In-App Notifications Mock Data
   ========================================================================= */

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    recipientId: 'vol-demo-1',
    type: 'NGO_OPPORTUNITY_PUBLISHED',
    title: 'New Drive from GreenCanopy Initiative',
    message: 'GreenCanopy Initiative posted a new drive: "Weekend Urban Reforestation & Native Seed Planting".',
    linkUrl: '/volunteer',
    read: false,
    createdAt: '2026-09-03T11:00:00Z',
  },
  {
    id: 'notif-2',
    recipientId: 'vol-demo-1',
    type: 'NGO_POST_PUBLISHED',
    title: 'New Impact Story from GreenCanopy',
    message: 'GreenCanopy shared: "Spring Watershed Restoration: 1,850 Native Trees Seeded".',
    linkUrl: '/volunteer/dashboard',
    read: false,
    createdAt: '2026-09-02T14:30:00Z',
  },
  {
    id: 'notif-3',
    recipientId: 'vol-demo-1',
    type: 'APPLICATION_STATUS_CHANGED',
    title: 'Commitment Confirmed',
    message: 'CodeForward Foundation confirmed your registration for "STEM Mentorship for Underrepresented Youth".',
    linkUrl: '/volunteer#commitments',
    read: true,
    createdAt: '2026-09-01T16:00:00Z',
  },
  {
    id: 'notif-4',
    recipientId: 'ngo-demo-1',
    type: 'CONNECTION_STATUS_CHANGED',
    title: 'CSR Partnership Inquiry Received',
    message: 'Apex Capital CSR Division requested an introductory briefing regarding your environmental drives.',
    linkUrl: '/ngo/corporate-partners',
    read: false,
    createdAt: '2026-09-02T12:00:00Z',
  },
  {
    id: 'notif-5',
    recipientId: 'corp-demo-1',
    type: 'NGO_POST_PUBLISHED',
    title: 'Impact Report: CodeForward Foundation',
    message: 'CodeForward published verified impact: "First-Generation College Admissions: 14 STEM Scholars Funded".',
    linkUrl: '/corporate/feed',
    read: false,
    createdAt: '2026-08-25T16:45:00Z',
  }
];

export const INITIAL_FOLLOWS = ['ngo-1', 'ngo-2'];
export const INITIAL_SHORTLIST = ['ngo-1', 'ngo-3'];
